const CAPTURE_SESSION_KEY='ptCaptureSessionV12';
const CAPTURE_SESSION_TTL=2*60*1000;
const MAX_SCREENSHOTS=6;
const MAX_SESSION_DATA_CHARS=7_000_000;
const state={bootstrap:null,currentTab:null,sourceUrl:'',sourceTitle:'',quote:'',shots:[],selectedTicket:'',list:'mine',searchRows:[],openTickets:[],lastClipboardFingerprint:'',clipboardAutoToken:0,sessionReady:false};
const $=id=>document.getElementById(id);
let persistTimer=0;
let searchSequence=0;
function showError(msg){$('error').textContent=msg;$('error').classList.toggle('hidden',!msg)}
function ticketUrl(id){const base=(state.bootstrap&&state.bootstrap.appUrl)||'';return base+(base.includes('?')?'&':'?')+'ticket='+encodeURIComponent(id)}
function detectElementContext(url){url=String(url||'');if(/\.451\.io\/.*(?:people|students|profile)/i.test(url))return 'Element451 student';if(/\.451\.io\/.*(?:workflow|campaign|form|event|segment|rule|import|export)/i.test(url))return 'Element451 resource';return ''}
function isGoogleEditor(url){return /^https:\/\/docs\.google\.com\/(?:document|spreadsheets)\//i.test(String(url||''))}
function uid(){return 'shot_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function fingerprint(dataUrl){const s=String(dataUrl||'');let h=2166136261;const sample=s.length>18000?s.slice(0,9000)+s.slice(-9000):s;for(let i=0;i<sample.length;i++){h^=sample.charCodeAt(i);h=Math.imul(h,16777619)}return s.length+':'+(h>>>0).toString(16)}
function totalShotChars(extra=''){return state.shots.reduce((n,s)=>n+String(s.dataUrl||'').length,0)+String(extra||'').length}
async function activeTabContext(){
  const [tab]=await chrome.tabs.query({active:true,currentWindow:true});
  state.currentTab=tab||null;
  state.sourceUrl=tab&&tab.url||'';
  state.sourceTitle=tab&&tab.title||'';
  if(tab&&tab.id){
    try{
      const [r]=await chrome.scripting.executeScript({
        target:{tabId:tab.id},
        func:()=>{
          let selection=String((window.getSelection&&window.getSelection())||'').trim();
          const ae=document.activeElement;
          if(!selection&&ae&&(ae.tagName==='TEXTAREA'||ae.tagName==='INPUT')&&Number.isInteger(ae.selectionStart)&&ae.selectionEnd>ae.selectionStart){
            selection=String(ae.value||'').slice(ae.selectionStart,ae.selectionEnd).trim();
          }
          return {selection,title:document.title,url:location.href};
        }
      });
      if(r&&r.result){
        if(r.result.selection)state.quote=r.result.selection;
        state.sourceTitle=r.result.title||state.sourceTitle;
        state.sourceUrl=r.result.url||state.sourceUrl;
      }
    }catch(e){}
  }
}
async function pendingContext(){const {pendingCapture}=await chrome.storage.local.get('pendingCapture');if(pendingCapture&&Date.now()-Number(pendingCapture.createdAt||0)<10*60*1000){state.sourceUrl=pendingCapture.sourceUrl||state.sourceUrl;state.sourceTitle=pendingCapture.sourceTitle||state.sourceTitle;if(pendingCapture.quote)state.quote=pendingCapture.quote;await chrome.storage.local.remove('pendingCapture')}}
async function restoreCaptureSession(){try{const out=await chrome.storage.session.get(CAPTURE_SESSION_KEY),s=out[CAPTURE_SESSION_KEY];if(!s||Number(s.expiresAt||0)<Date.now()){await chrome.storage.session.remove(CAPTURE_SESSION_KEY);return}state.shots=Array.isArray(s.shots)?s.shots.filter(x=>x&&x.dataUrl).slice(0,MAX_SCREENSHOTS):[];state.selectedTicket=String(s.selectedTicket||'');state.lastClipboardFingerprint=String(s.lastClipboardFingerprint||'');if(!state.quote&&s.quote)state.quote=String(s.quote);if($('note')&&s.note)$('note').value=String(s.note);state.sessionReady=true}catch(e){console.warn('Could not restore temporary capture session',e)}}
async function persistCaptureSession(){if(!state.sessionReady)return;const payload={shots:state.shots,selectedTicket:state.selectedTicket,lastClipboardFingerprint:state.lastClipboardFingerprint,quote:state.quote,note:$('note')?$('note').value:'',expiresAt:Date.now()+CAPTURE_SESSION_TTL};try{await chrome.storage.session.set({[CAPTURE_SESSION_KEY]:payload})}catch(e){console.warn('Could not cache capture session',e)}}
function schedulePersistCaptureSession(delay=250){clearTimeout(persistTimer);persistTimer=setTimeout(()=>{persistTimer=0;persistCaptureSession()},delay)}
async function flushPersistCaptureSession(){if(persistTimer){clearTimeout(persistTimer);persistTimer=0}await persistCaptureSession()}
async function clearCaptureSession(){state.shots=[];state.quote='';state.lastClipboardFingerprint='';if($('note'))$('note').value='';try{await chrome.storage.session.remove(CAPTURE_SESSION_KEY)}catch(e){}}
function renderContext(){$('sourceTitle').textContent=state.sourceTitle||'Current browser tab';$('sourceUrl').textContent=state.sourceUrl;const c=detectElementContext(state.sourceUrl);$('elementContext').textContent=c;$('elementContext').classList.toggle('hidden',!c);$('quoteWrap').classList.toggle('hidden',!state.quote);$('quotePreview').textContent=state.quote||'';$('googleSelectionWrap').classList.toggle('hidden',!isGoogleEditor(state.sourceUrl)||!!state.quote);$('createTitle').value=$('createTitle').value||state.sourceTitle||''}
async function openProjectTickets(){const tabs=await chrome.tabs.query({});const ids=new Map();for(const t of tabs){const u=String(t.url||'');if(!/[?&]ticket=TKT-\d+/i.test(u))continue;if(!/Project Tracker/i.test(String(t.title||''))&&!/script\.google\.com/i.test(u))continue;const m=u.match(/[?&]ticket=(TKT-\d+)/i);if(m&&!ids.has(m[1].toUpperCase()))ids.set(m[1].toUpperCase(),{ticket_id:m[1].toUpperCase(),title:String(t.title||'').replace(/\s*[-|·].*Project Tracker.*$/i,'')||m[1],tabId:t.id})}state.openTickets=[...ids.values()]}
async function hydrateOpenTicketDetails(){if(!state.openTickets.length)return;const known=new Map();if(state.bootstrap){[...(state.bootstrap.mine||[]),...(state.bootstrap.mentioned||[])].forEach(r=>{const id=String(r&&r.ticket_id||'').toUpperCase();if(id&&!known.has(id))known.set(id,r)})}const unresolved=[];state.openTickets.forEach(t=>{const exact=known.get(t.ticket_id);if(exact){t.title=exact.title||t.title;t.type=exact.type||t.type;t.department=exact.department||t.department;t.size=exact.size||t.size}else unresolved.push(t)});renderTickets();if(!unresolved.length)return;const results=await Promise.allSettled(unresolved.map(t=>PTApi.search(t.ticket_id)));results.forEach((result,i)=>{const t=unresolved[i];if(result.status!=='fulfilled'){console.warn('Could not resolve open ticket title',t.ticket_id,result.reason);return}const rows=(result.value&&result.value.rows)||[];const exact=rows.find(r=>String(r.ticket_id||'').toUpperCase()===t.ticket_id);if(exact){t.title=exact.title||t.title;t.type=exact.type||t.type;t.department=exact.department||t.department;t.size=exact.size||t.size}});renderTickets()}
function ticketRow(t){const b=document.createElement('button');b.className='ticket-row'+(state.selectedTicket===t.ticket_id?' on':'');b.dataset.ticket=t.ticket_id;b.innerHTML=`<span class="ticket-size">${t.size||'—'}</span><span class="ticket-main"><span class="ticket-title"></span><span class="ticket-meta"></span></span>`;b.querySelector('.ticket-title').textContent=t.title||t.ticket_id;b.querySelector('.ticket-meta').textContent=[t.ticket_id,t.type,t.department].filter(Boolean).join(' · ');b.addEventListener('click',()=>{state.selectedTicket=t.ticket_id;renderTickets();persistCaptureSession()});return b}
function listRows(){if(!state.bootstrap)return[];if(state.list==='mentioned')return state.bootstrap.mentioned||[];if(state.list==='search')return state.searchRows||[];return state.bootstrap.mine||[]}
function renderTickets(){const openHost=$('openTicketList');openHost.innerHTML='';$('openTickets').classList.toggle('hidden',!state.openTickets.length);state.openTickets.forEach(t=>openHost.appendChild(ticketRow(t)));const host=$('ticketList');host.innerHTML='';const rows=listRows();if(!rows.length){host.innerHTML='<div class="empty">No tickets here.</div>'}else rows.forEach(t=>host.appendChild(ticketRow(t)));$('saveCapture').disabled=!state.selectedTicket;$('openSelected').disabled=!state.selectedTicket;document.querySelectorAll('[data-list]').forEach(b=>b.classList.toggle('on',b.dataset.list===state.list));$('searchWrap').classList.toggle('hidden',state.list!=='search')}
function blobToDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=rej;r.readAsDataURL(blob)})}
function optimizeDataUrl(dataUrl){return new Promise(resolve=>{if(!dataUrl){resolve('');return}const img=new Image();img.onload=()=>{const max=1500,scale=Math.min(1,max/Math.max(img.width,img.height));if(scale===1&&dataUrl.length<1800000){resolve(dataUrl);return}const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};img.onerror=()=>resolve(dataUrl);img.src=dataUrl})}
async function readClipboardImage(){try{const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(t=>t.startsWith('image/'));if(type){const blob=await item.getType(type);const dataUrl=await optimizeDataUrl(await blobToDataUrl(blob));return{dataUrl,fingerprint:fingerprint(dataUrl)}}}}catch(e){}return null}
function addShot(dataUrl,kind,sourceUrl=state.sourceUrl,sourceTitle=state.sourceTitle,fp=''){if(!dataUrl)return false;fp=fp||fingerprint(dataUrl);if(state.shots.some(s=>s.fingerprint===fp))return false;if(state.shots.length>=MAX_SCREENSHOTS){showError(`You can stack up to ${MAX_SCREENSHOTS} screenshots in one note.`);return false}if(totalShotChars(dataUrl)>MAX_SESSION_DATA_CHARS){showError('Those screenshots are getting too large for one note. Add the current batch to the ticket, then start another note.');return false}state.shots.push({id:uid(),dataUrl,fingerprint:fp,kind:kind||'clipboard',sourceUrl:String(sourceUrl||''),sourceTitle:String(sourceTitle||''),capturedAt:new Date().toISOString()});renderShots();persistCaptureSession();return true}
function renderShots(){const host=$('shotList');host.innerHTML='';$('imagePreviewWrap').classList.toggle('hidden',!state.shots.length);$('clipboardBadge').classList.toggle('hidden',!state.shots.some(s=>s.kind==='clipboard'));$('saveAddAnother').disabled=!state.shots.length;$('shotCount').textContent=state.shots.length?`${state.shots.length} screenshot${state.shots.length===1?'':'s'} queued`:'';state.shots.forEach((shot,i)=>{const row=document.createElement('div');row.className='shot-row';row.innerHTML='<img alt="Screenshot preview"><div class="shot-meta"><b></b><span></span></div><button class="shot-remove" title="Remove screenshot">×</button>';row.querySelector('img').src=shot.dataUrl;row.querySelector('b').textContent=`Screenshot ${i+1}`;row.querySelector('span').textContent=shot.sourceTitle||shot.sourceUrl||'Browser capture';row.querySelector('.shot-remove').addEventListener('click',()=>{state.shots=state.shots.filter(x=>x.id!==shot.id);renderShots();persistCaptureSession()});host.appendChild(row)})}
async function autoClipboardImage(){const token=state.clipboardAutoToken;const found=await readClipboardImage();if(token!==state.clipboardAutoToken||!found)return false;if(found.fingerprint===state.lastClipboardFingerprint||state.shots.some(s=>s.fingerprint===found.fingerprint))return false;state.lastClipboardFingerprint=found.fingerprint;addShot(found.dataUrl,'clipboard',state.sourceUrl,state.sourceTitle,found.fingerprint);return true}
async function markCurrentClipboardSeen(){const found=await readClipboardImage();if(found){state.lastClipboardFingerprint=found.fingerprint;await persistCaptureSession()}}
async function useClipboardExplicit(){state.clipboardAutoToken++;const found=await readClipboardImage();if(!found){showError('No image is currently available on the clipboard.');return false}state.lastClipboardFingerprint=found.fingerprint;if(!addShot(found.dataUrl,'clipboard',state.sourceUrl,state.sourceTitle,found.fingerprint))showError(state.shots.some(s=>s.fingerprint===found.fingerprint)?'That clipboard screenshot is already queued.':'');else showError('');return true}
async function captureVisible(){state.clipboardAutoToken++;markCurrentClipboardSeen();try{const dataUrl=await optimizeDataUrl(await chrome.tabs.captureVisibleTab(state.currentTab&&state.currentTab.windowId,{format:'png'}));addShot(dataUrl,'visible',state.sourceUrl,state.sourceTitle);showError('')}catch(e){showError('Chrome could not capture this tab. Try the clipboard screenshot instead.')}}
async function clearScreenshots(){state.clipboardAutoToken++;await markCurrentClipboardSeen();state.shots=[];renderShots();await persistCaptureSession();showError('')}
async function snapshotClipboard(){try{const items=await navigator.clipboard.read();const saved=[];for(const item of items){const types={};for(const type of item.types){try{const blob=await item.getType(type);if(!window.ClipboardItem||!ClipboardItem.supports||ClipboardItem.supports(type))types[type]=blob}catch(e){}}if(Object.keys(types).length)saved.push(types)}return saved}catch(e){return[]}}
async function restoreClipboard(saved){if(!saved||!saved.length||!navigator.clipboard.write||!window.ClipboardItem)return false;try{await navigator.clipboard.write(saved.map(types=>new ClipboardItem(types)));return true}catch(e){return false}}
async function importGoogleEditorSelection(){const btn=$('importGoogleSelection');btn.disabled=true;btn.textContent='Reading clipboard…';state.clipboardAutoToken++;try{const text=String(await navigator.clipboard.readText()||'').trim();if(!text)throw new Error('Nothing copied yet. In Google Docs/Sheets, highlight the text or cells and press Ctrl+C (Cmd+C on Mac), then click this button.');state.quote=text;renderContext();await persistCaptureSession();showError('')}catch(e){showError(e.message||String(e))}finally{btn.disabled=false;btn.textContent='Use copied text as quote'}}
function mentionQuery(){const ta=$('note'),pos=ta.selectionStart||0,before=ta.value.slice(0,pos),m=before.match(/(?:^|\s)@([A-Za-z.]*)$/);return m?{query:m[1].toLowerCase(),start:pos-m[1].length-1,end:pos}:null}
function renderMentionMenu(){const info=mentionQuery(),menu=$('mentionMenu');if(!info||!state.bootstrap){menu.classList.add('hidden');return}const agents=(state.bootstrap.agents||[]).filter(a=>String(a.role||'').toLowerCase()!=='viewer').filter(a=>{const n=String(a.name||'').toLowerCase(),e=String(a.email||'').toLowerCase();return !info.query||n.includes(info.query)||e.includes(info.query)}).slice(0,6);if(!agents.length){menu.classList.add('hidden');return}menu.innerHTML='';agents.forEach(a=>{const b=document.createElement('button');b.type='button';b.className='mention-option';b.innerHTML='<b></b><span></span>';b.querySelector('b').textContent=a.name;b.querySelector('span').textContent=a.email;b.addEventListener('mousedown',e=>{e.preventDefault();const ta=$('note'),first=String(a.name||'').trim().split(/\s+/)[0]||String(a.email||'').split('@')[0];ta.setRangeText('@'+first+' ',info.start,info.end,'end');menu.classList.add('hidden');ta.focus();persistCaptureSession()});menu.appendChild(b)});menu.classList.remove('hidden')}
async function saveCapture(){if(!state.selectedTicket)return;const btn=$('saveCapture');btn.disabled=true;btn.textContent='Adding…';try{await PTApi.capture({ticketId:state.selectedTicket,note:$('note').value,quote:state.quote,sourceUrl:state.sourceUrl,sourceTitle:state.sourceTitle,screenshots:state.shots.map(s=>({dataUrl:s.dataUrl,sourceUrl:s.sourceUrl,sourceTitle:s.sourceTitle,capturedAt:s.capturedAt,kind:s.kind})),addPageContext:true});btn.textContent='Added ✓';await clearCaptureSession();renderShots();renderContext();setTimeout(()=>{btn.textContent='Add to ticket';btn.disabled=false},1200);showError('')}catch(e){showError(e.message);btn.textContent='Add to ticket';btn.disabled=false}}
async function saveAndAddAnother(){if(!state.shots.length)return;await persistCaptureSession();showError('');window.close()}
async function load(){let bootstrapValue=null,bootstrapError=null;const bootstrapPromise=PTApi.bootstrap().then(v=>{bootstrapValue=v},e=>{bootstrapError=e});const openTicketsPromise=openProjectTickets().catch(e=>console.warn('Could not inspect open Project Tracker tabs',e));try{await activeTabContext();await pendingContext();state.sessionReady=true;await restoreCaptureSession();renderContext();renderShots();await Promise.all([bootstrapPromise,openTicketsPromise]);if(bootstrapError)throw bootstrapError;state.bootstrap=bootstrapValue;$('connectWrap').classList.add('hidden');$('identity').textContent=state.bootstrap.me||'';const typeSel=$('createType'),deptSel=$('createDepartment');(state.bootstrap.types||[]).forEach(t=>{const o=document.createElement('option');o.value=t.name;o.textContent=t.name;typeSel.appendChild(o)});(state.bootstrap.departments||[]).forEach(d=>{const o=document.createElement('option');o.value=d;o.textContent=d;deptSel.appendChild(o)});if(!state.selectedTicket&&state.openTickets.length===1)state.selectedTicket=state.openTickets[0].ticket_id;renderTickets();await persistCaptureSession();hydrateOpenTicketDetails().catch(e=>console.warn('Could not hydrate open ticket details',e));autoClipboardImage()}catch(e){showError(e.message);$('identity').textContent='Not connected';if(/authorization|connect google|oauth setup/i.test(String(e.message||e)))$('connectWrap').classList.remove('hidden')}}
$('connectGoogle').addEventListener('click',async()=>{const b=$('connectGoogle');b.disabled=true;b.textContent='Connecting…';try{state.bootstrap=await PTApi.connect();$('identity').textContent=state.bootstrap.me||'';$('connectWrap').classList.add('hidden');showError('');renderTickets()}catch(e){showError(e.message)}finally{b.disabled=false;b.textContent='Connect Google'}});
$('settings').addEventListener('click',()=>chrome.runtime.openOptionsPage());
$('clearQuote').addEventListener('click',()=>{state.quote='';renderContext();persistCaptureSession()});
$('importGoogleSelection').addEventListener('click',importGoogleEditorSelection);
$('captureTab').addEventListener('click',captureVisible);
$('useClipboard').addEventListener('click',useClipboardExplicit);
$('noImage').addEventListener('click',clearScreenshots);
$('saveAddAnother').addEventListener('click',saveAndAddAnother);
$('saveCapture').addEventListener('click',saveCapture);
$('openSelected').addEventListener('click',()=>{if(state.selectedTicket)chrome.tabs.create({url:ticketUrl(state.selectedTicket)})});
$('note').addEventListener('input',()=>{renderMentionMenu();schedulePersistCaptureSession()});$('note').addEventListener('click',renderMentionMenu);$('note').addEventListener('keyup',e=>{if(e.key==='Escape')$('mentionMenu').classList.add('hidden')});$('note').addEventListener('blur',()=>setTimeout(()=>$('mentionMenu').classList.add('hidden'),120));
document.querySelectorAll('[data-list]').forEach(b=>b.addEventListener('click',()=>{state.list=b.dataset.list;renderTickets();if(state.list==='search')$('search').focus()}));let searchTimer;$('search').addEventListener('input',()=>{clearTimeout(searchTimer);const q=$('search').value.trim(),seq=++searchSequence;if(q.length<2){state.searchRows=[];renderTickets();return}searchTimer=setTimeout(async()=>{try{const out=await PTApi.search(q);if(seq!==searchSequence)return;state.searchRows=out.rows||[];renderTickets()}catch(e){if(seq===searchSequence)showError(e.message)}},300)});
$('createTicket').addEventListener('click',async()=>{const b=$('createTicket');b.disabled=true;b.textContent='Creating…';try{const out=await PTApi.create({title:$('createTitle').value,sourceUrl:state.sourceUrl,sourceTitle:state.sourceTitle,note:$('note').value,quote:state.quote,screenshots:state.shots.map(s=>({dataUrl:s.dataUrl,sourceUrl:s.sourceUrl,sourceTitle:s.sourceTitle,capturedAt:s.capturedAt,kind:s.kind})),type:$('createType').value,department:$('createDepartment').value,size:$('createSize').value,addPageContext:true});state.selectedTicket=out.ticket.ticket_id;state.bootstrap.mine.unshift(out.ticket);await clearCaptureSession();renderShots();renderContext();renderTickets();b.textContent='Created ✓';setTimeout(()=>b.textContent='Create + add current context',1200)}catch(e){showError(e.message);b.textContent='Create + add current context'}finally{b.disabled=false}});
setInterval(()=>persistCaptureSession(),30000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushPersistCaptureSession()});
load();
